dist: xenial
language: scala
install:
  - |
    # update this only when sbt-the-bash-script needs to be updated
    export SBT_LAUNCHER=1.4.9
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
    tar zxf $HOME/sbt.tgz -C $HOME
    sudo rm /usr/local/bin/sbt
    sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt
script:
  - ./run.sh $SCALA_BRANCH
scala:
  # This is actually overridden by the run.sh script
  - 2.13.5
jdk:
  - openjdk8
env:
  - SCALA_BRANCH=2.11.x
  - SCALA_BRANCH=2.12.x
  - SCALA_BRANCH=2.13.x

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete

notifications:
  email:
    - miles@milessabin.com
